apiVersion: v1
kind: Service
metadata:
  name: listeninghistory
  labels:
    app: listeninghistory
spec:
  ports:
  - port: 8000
    protocol: TCP
  clusterIP: None
  selector:
    app: listeninghistory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listeninghistory
  labels:
    app: listeninghistory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listeninghistory
  template:
    metadata:
      labels:
        app: listeninghistory
    spec:
      containers:
      - name: listeninghistory
        image: listeninghistory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listeninghistory-database
  labels:
    app: listeninghistory-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listeninghistory-database
  template:
    metadata:
      labels:
        app: listeninghistory-database
    spec:
      containers:
      - name: listeninghistory-database
        image: postgres:13-alpine
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "1234"
---
apiVersion: v1
kind: Service
metadata:
  name: listeninghistory-database-service
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: listeninghistory-database
