apiVersion: v1
kind: Service
metadata:
  name: musiclibrary
  labels:
    app: musiclibrary
spec:
  ports:
  - port: 8000
  selector:
    app: musiclibrary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: musiclibrary
  labels:
    app: musiclibrary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musiclibrary
  template:
    metadata:
      labels:
        app: musiclibrary
    spec:
      containers:
      - name: musiclibrary
        image: musiclibrary
        volumeMounts:
          - name: discogss
            mountPath: /discogs
      volumes:
      - hostPath:
          path: /discogs
        name: discogss
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: musiclibrary-database
  labels:
    app: musiclibrary-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musiclibrary-database
  template:
    metadata:
      labels:
        app: musiclibrary-database
    spec:
      containers:
      - name: musiclibrary-database
        image: postgres:13-alpine
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "1234"
---
apiVersion: v1
kind: Service
metadata:
  name: musiclibrary-database-service
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: musiclibrary-database
